### ISSUE TITLE
Issue connecting to http://localhost:8183/

### ISSUE THREAD

**Issue by FlxDrv** [Selbi182/SpotifyBigPicture#14]
Hi!

So I tried instaling spotify big picture, worked my way through the instalation process when i encountered my first hurdle.
When i launched Start_SpotifyBigPicture.sh i would get an error along the lines that it couldn't connect. And the port was already in use.

Sure enough, after typing (netstat -ano -p tcp |find "8183") in the CMD, i found that something was already listening to the port. So i close the program through task manager sinci CMD was showing me the PID of the program using the port.

After doing the the issue went away and i "got SpotifyBigPicture is ready! URL: http://localhost:8183" prompted on the console when opening Start_SpotifyBigPicture.sh. However, now, I can't open "Start_SpotifyBigPicture.sh" i get "local host does not allow the connection" with "ERR_CONNECTION_REFUSED" as the error code. Idk what to do now :(

I think it's probably an issue on my end tbh but idk how to resolve it.

Also when i installed the program, when it asked for the access on public and private networks. I only ticked for public and not for private, could this be the issue?

Thanks in advance :)

**Comment by Selbi182** [comment]
I THINK the privacy stuff may be the problem. I'm not 100% sure though. Can you try to changing that to public and see if that fixes it?

Apart from that, it sounds like you're trying to start a new instance while the old one was still running. Did it work the first time you got the ready message?

**Comment by FlxDrv** [comment]
I wanted to change it to public but idk the name of the application in windows, so i can't find it back to change the setting.

Also even when launching from a fresh boot, it still does this, and no it didn't work the first time i got the ready message

**Comment by Selbi182** [comment]
https://support.microsoft.com/en-us/windows/risks-of-allowing-apps-through-windows-defender-firewall-654559af-3f54-3dcf-349f-71ccd90bcc5c

The app is simply run on Java, so it won't be listed there with a real name. To me, it's simply called OpenJDK Platform binary:

![grafik](https://user-images.githubusercontent.com/8850085/221445731-806f511e-5c8b-4d7a-8f72-38ffc27df1ef.png)

Since I didn't know which one was which, I removed them all.

However, I did just try to restart the app and explicitely not allowing anything. It still worked without problem though. I'm not sure if this is due to some caching nonsense or because the firewall was never the problem in the first place.

Anyway, give that a try and tell me if it works.

**Comment by FlxDrv** [comment]
OMG i made it work ahahah, i just had to start "Start_SpotifyBigPicture.sh" while the "http://localhost:8183/" page was still loading.

Also yes That's the app I ticked back on when i tried to re-tick it manually after i forgot to do it. But I wasn't sure if it was the right app.

Thanks against mate! The page looks awsome :)

**Comment by Selbi182** [comment]
Hahaha, no worries. I'm glad you got it running! :)
