### ISSUE TITLE
Liked Songs fall to fallback playlist name

### ISSUE THREAD

**Issue by Invy55** [Selbi182/SpotifyBigPicture#17]
Hi, thanks for this incredible piece of app you have created! (Starred right away)

I was playing with it when I noticed that liked songs don't get in the top context ever, it says this: fallback:track
![immagine](https://user-images.githubusercontent.com/38048104/222925768-47f390e2-9150-4160-9fbc-41e1fed9ac5a.png)

or if you had already played another playlist it keeps it's name.

No error is shown in the console, so I'm opening this issue

**Comment by Selbi182** [comment]
First of all, good taste! The Weeknd is amazing 😍

As for the bug, you're right, I never programmed playing from liked song context... I'll fix that asap. Thanks for letting me know! 

As for no error, that was intentional. Fallback is meant to be a catch-all solution for everything I've forgotten.

Are there any more contexts I've forgotten? It would be amazing if you could help me and play around :)

**Comment by Invy55** [comment]
> First of all, good taste! The Weeknd is amazing 😍
> 
> As for the bug, you're right, I never programmed playing from liked song context... I'll fix that asap. Thanks for letting me know!
> 
> As for no error, that was intentional. Fallback is meant to be a catch-all solution for everything I've forgotten.
> 
> Are there any more contexts I've forgotten? It would be amazing if you could help me and play around :)

wow, what a quick reply. I see what you're saying. I'm testing it a bit because having a second monitor I wanted to keep this as my background using Lively Wallpaper.

About top contexts, I found out that Daily Drive also doesn't have it and apparently it does not update the player at all.
![immagine](https://user-images.githubusercontent.com/38048104/222926083-02d5b56b-0c67-411a-a113-b4100b4f284c.png)
I used to play a bit with spotify apis and I seem to remeber that podcasts aren't in it so that's not an issue at all, however songs doesn't work too if from that playlist.

**Comment by Selbi182** [comment]
Podcasts should work. They've extended the API a while ago to finally support them.

As for the Daily Drive, that's another feature of Spotify I've never used, so that's why I forgot to include it. Will also be fixed asap 👌

**Comment by Invy55** [comment]
![immagine](https://user-images.githubusercontent.com/38048104/222926420-25c4ef18-257a-4fc7-a803-e51d927a8c8f.png)
what 🫥

**Comment by Selbi182** [comment]
Hahaha, expect weird things to happen when your programmer forgets stuff

**Comment by Selbi182** [comment]
Okay, good and bad news. The good news is that Liked Songs and Daily Drive work now:

![grafik](https://user-images.githubusercontent.com/8850085/222931638-78dbb684-ad45-4d12-ac4a-244722d4284f.png)
![grafik](https://user-images.githubusercontent.com/8850085/222932070-68dc5b4e-bc91-46f3-b9ab-1b20e1246b57.png)

The bad news is that I have no way to get Daily Drive to run without any problems. I've just pulled my hair out trying to get it to work, but Spotify seems to provide different data for podcasts inside Daily Drive than the actual episode for some weird reason. I've tried my best to cover their shortcomings, but if the tracklist ever gets slightly wonky, you know where the problem is.

Anyway, I have updated the current release (https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v1.0). Since I only released it a couple of hours before you made this thread, I don't feel like making a new release altogether, heh.

Please report back if these things work now!

**Comment by Invy55** [comment]
> Okay, good and bad news. The good news is that Liked Songs and Daily Drive work now:
> 
> ![grafik](https://user-images.githubusercontent.com/8850085/222931638-78dbb684-ad45-4d12-ac4a-244722d4284f.png) ![grafik](https://user-images.githubusercontent.com/8850085/222932070-68dc5b4e-bc91-46f3-b9ab-1b20e1246b57.png)
> 
> The bad news is that I have no way to get Daily Drive to run without any problems. I've just pulled my hair out trying to get it to work, but Spotify seems to provide different data for podcasts inside Daily Drive than the actual episode for some weird reason. I've tried my best to cover their shortcomings, but if the tracklist ever gets slightly wonky, you know where the problem is.
> 
> Anyway, I have updated the current release (https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v1.0). Since I only released it a couple of hours before you made this thread, I don't feel like making a new release altogether, heh.
> 
> Please report back if these things work now!

You are insane. Everything is working, daily drive included. I will do further testing and will report back if I find any more issues. Thanks for this incredible support you provided. 😊

**Comment by Invy55** [comment]
![immagine](https://user-images.githubusercontent.com/38048104/222964962-33fc42e3-223f-4020-9105-32a7da3b8dfc.png)
![immagine](https://user-images.githubusercontent.com/38048104/222964979-43b4de7a-5eed-414d-ad91-e8e2a0f021a4.png)
Found an issue, when I search and play directly a song, if I then play back my liked songs this happens. This doens't happen with anything else like playlists or artists.

**Comment by Selbi182** [comment]
Fixed. Again.

And updated release v1.0. Again...

Thanks for your reports 😂 👍
